"""
Dry-run output — generates CloudFormation parameter files and a ready-to-run
deploy shell script without touching any AWS resources.

Outputs written to a directory (default: ./coder-deploy-<cluster>):
  ├── pipeline-parameters.json      CF parameter overrides for Step 1
  ├── core-parameters.json          CF parameter overrides for Step 2
  ├── deploy.sh                     Fully-formed aws cloudformation CLI commands
  └── dry-run-summary.txt           Human-readable summary of what would happen
"""

from __future__ import annotations

import json
import stat
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path


@dataclass
class DryRunOutput:
    output_dir: Path
    pipeline_params_path: Path
    core_params_path: Path
    deploy_script_path: Path
    summary_path: Path


def _cfn_param_list(params: dict) -> list[dict]:
    """Convert a plain dict to CloudFormation parameter list format."""
    return [
        {"ParameterKey": k, "ParameterValue": v}
        for k, v in params.items()
    ]


def generate(
    output_dir: str,
    region: str,
    cluster: str,
    pipeline_template: str,
    core_template: str,
    pipeline_params: dict,
    core_params: dict,
    pipeline_stack_name: str,
    core_stack_name: str,
    estimated_monthly_cost: float,
    developer_count: int,
    spot_fraction: float = 0.0,
) -> DryRunOutput:
    """
    Write parameter files and a deploy script to output_dir.
    Returns paths to every file created.
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    # ── pipeline-parameters.json ───────────────────────────────────────────
    pipeline_params_path = out / "pipeline-parameters.json"
    pipeline_params_path.write_text(
        json.dumps(_cfn_param_list(pipeline_params), indent=2)
    )

    # ── core-parameters.json ──────────────────────────────────────────────
    core_params_path = out / "core-parameters.json"
    # Redact secrets so the file is safe to commit / share
    safe_core = dict(core_params)
    if "CoderAdminPassword" in safe_core:
        safe_core["CoderAdminPassword"] = "REDACTED_RETRIEVE_FROM_SECRETS_MANAGER"
    if safe_core.get("CoderLicenseKey"):
        safe_core["CoderLicenseKey"] = "REDACTED_PREMIUM_LICENSE_JWT"
    core_params_path.write_text(
        json.dumps(_cfn_param_list(safe_core), indent=2)
    )

    # ── deploy.sh ─────────────────────────────────────────────────────────
    pipeline_abs = str(Path(pipeline_template).resolve())
    core_abs     = str(Path(core_template).resolve())

    script_lines = [
        "#!/usr/bin/env bash",
        "# Generated by partner-coder-wizard --dry-run",
        f"# Generated at: {datetime.now(tz=timezone.utc).isoformat()}",
        f"# Region       : {region}",
        f"# EKS cluster  : {cluster}",
        f"# Est. cost     : ~${estimated_monthly_cost:,.0f}/month ({developer_count} developers, {spot_fraction*100:.0f}% on Spot)",
        "#",
        "# Review this script, then run:  bash deploy.sh",
        "# To deploy a single step:  bash deploy.sh step1   or   bash deploy.sh step2",
        "",
        "set -euo pipefail",
        "",
        f'REGION="{region}"',
        f'PIPELINE_STACK="{pipeline_stack_name}"',
        f'CORE_STACK="{core_stack_name}"',
        f'PIPELINE_TEMPLATE="{pipeline_abs}"',
        f'CORE_TEMPLATE="{core_abs}"',
        f'OUTPUT_DIR="{out.resolve()}"',
        "",
        'STEP="${1:-all}"',
        "",
        "# ── Helper ──────────────────────────────────────────────────────",
        "wait_for_stack() {",
        '  local stack="$1"',
        '  echo "Waiting for stack $stack …"',
        "  aws cloudformation wait stack-create-complete \\",
        '    --stack-name "$stack" \\',
        '    --region "$REGION"',
        "}",
        "",
        "# ── Helper: inline --template-body for small templates, else stage to",
        "# S3 and use --template-url (CloudFormation inline limit is 51,200 bytes).",
        "TEMPLATE_BODY_MAX=51200",
        "template_arg() {",
        '  local tpl="$1"',
        '  local size; size=$(wc -c < "$tpl")',
        '  if [ "$size" -le "$TEMPLATE_BODY_MAX" ]; then',
        '    echo "--template-body file://$tpl"',
        "    return",
        "  fi",
        '  local account; account=$(aws sts get-caller-identity --query Account --output text)',
        '  local bucket="coder-wizard-templates-${account}-${REGION}"',
        '  if ! aws s3api head-bucket --bucket "$bucket" --region "$REGION" 2>/dev/null; then',
        '    if [ "$REGION" = "us-east-1" ]; then',
        '      aws s3api create-bucket --bucket "$bucket" --region "$REGION" >/dev/null',
        "    else",
        '      aws s3api create-bucket --bucket "$bucket" --region "$REGION" \\',
        '        --create-bucket-configuration "LocationConstraint=$REGION" >/dev/null',
        "    fi",
        '    aws s3api put-public-access-block --bucket "$bucket" --region "$REGION" \\',
        '      --public-access-block-configuration BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true >/dev/null 2>&1 || true',
        '    aws s3api put-bucket-encryption --bucket "$bucket" --region "$REGION" \\',
        "      --server-side-encryption-configuration '{\"Rules\":[{\"ApplyServerSideEncryptionByDefault\":{\"SSEAlgorithm\":\"AES256\"}}]}' >/dev/null 2>&1 || true",
        '    aws s3api put-bucket-lifecycle-configuration --bucket "$bucket" --region "$REGION" \\',
        "      --lifecycle-configuration '{\"Rules\":[{\"ID\":\"expire-staged-templates\",\"Filter\":{\"Prefix\":\"\"},\"Status\":\"Enabled\",\"Expiration\":{\"Days\":7},\"AbortIncompleteMultipartUpload\":{\"DaysAfterInitiation\":1}}]}' >/dev/null 2>&1 || true",
        "  fi",
        '  local key; key="$(basename "$tpl")"',
        '  aws s3 cp "$tpl" "s3://$bucket/$key" --region "$REGION" >/dev/null',
        '  if [ "$REGION" = "us-east-1" ]; then',
        '    echo "--template-url https://$bucket.s3.amazonaws.com/$key"',
        "  else",
        '    echo "--template-url https://$bucket.s3.$REGION.amazonaws.com/$key"',
        "  fi",
        "}",
        "",
        "# ── Step 1: Image pipeline ──────────────────────────────────────",
        'if [[ "$STEP" == "all" || "$STEP" == "step1" ]]; then',
        '  echo "=== Step 1: Deploying image pipeline stack: $PIPELINE_STACK ==="',
        "  aws cloudformation create-stack \\",
        '    --stack-name "$PIPELINE_STACK" \\',
        '    $(template_arg "$PIPELINE_TEMPLATE") \\',
        '    --parameters "file://$OUTPUT_DIR/pipeline-parameters.json" \\',
        "    --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \\",
        '    --region "$REGION"',
        "",
        '  wait_for_stack "$PIPELINE_STACK"',
        "",
        "  # Wait for the CodeBuild workspace image build to complete",
        f'  CODEBUILD_PROJECT="{cluster}-workspace-image-build"',
        '  echo "Waiting for CodeBuild project $CODEBUILD_PROJECT to finish building images…"',
        "  BUILD_ID=$(aws codebuild list-builds-for-project \\",
        '    --project-name "$CODEBUILD_PROJECT" \\',
        '    --region "$REGION" \\',
        "    --query 'ids[0]' --output text)",
        "  aws codebuild batch-get-builds --ids \"$BUILD_ID\" \\",
        "    --region \"$REGION\" \\",
        "    --query 'builds[0].buildStatus' --output text",
        '  echo "Step 1 complete."',
        "fi",
        "",
        "# ── Step 2: Core Coder stack ────────────────────────────────────",
        'if [[ "$STEP" == "all" || "$STEP" == "step2" ]]; then',
        '  echo "=== Step 2: Deploying core Coder stack: $CORE_STACK ==="',
        "  # NOTE: CoderAdminPassword (and CoderLicenseKey, if used) are REDACTED",
        "  # in core-parameters.json. Replace them or add --parameter overrides.",
        "  aws cloudformation create-stack \\",
        '    --stack-name "$CORE_STACK" \\',
        '    $(template_arg "$CORE_TEMPLATE") \\',
        '    --parameters "file://$OUTPUT_DIR/core-parameters.json" \\',
        "    --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \\",
        '    --region "$REGION"',
        "",
        '  wait_for_stack "$CORE_STACK"',
        '  echo "Step 2 complete."',
        "fi",
        "",
        "# ── Outputs ─────────────────────────────────────────────────────",
        'if [[ "$STEP" == "all" ]]; then',
        '  echo "=== Deployment complete. Stack outputs: ==="',
        "  aws cloudformation describe-stacks \\",
        '    --stack-name "$CORE_STACK" \\',
        '    --region "$REGION" \\',
        "    --query 'Stacks[0].Outputs' \\",
        "    --output table",
        "fi",
    ]

    deploy_script_path = out / "deploy.sh"
    deploy_script_path.write_text("\n".join(script_lines) + "\n")
    deploy_script_path.chmod(
        deploy_script_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP
    )

    # ── dry-run-summary.txt ───────────────────────────────────────────────
    summary_lines = [
        "Partner Demo Coder Install Wizard — Dry Run Summary",
        f"Generated : {datetime.now(tz=timezone.utc).isoformat()}",
        "",
        "CONFIGURATION",
        f"  Region          : {region}",
        f"  EKS cluster     : {cluster}",
        f"  Developers      : {developer_count}",
        f"  Spot lane share : {spot_fraction*100:.0f}%",
        f"  Est. cost       : ~${estimated_monthly_cost:,.0f}/month",
        "",
        "STACKS TO BE CREATED",
        f"  Step 1 (image pipeline)  : {pipeline_stack_name}",
        f"    Template               : {pipeline_abs}",
        f"    Parameters file        : {pipeline_params_path.resolve()}",
        "",
        f"  Step 2 (core Coder)      : {core_stack_name}",
        f"    Template               : {core_abs}",
        f"    Parameters file        : {core_params_path.resolve()}",
        "",
        "PIPELINE PARAMETERS",
    ]
    for k, v in pipeline_params.items():
        summary_lines.append(f"  {k:<40} {v}")

    summary_lines += [
        "",
        "CORE PARAMETERS",
    ]
    for k, v in safe_core.items():
        summary_lines.append(f"  {k:<40} {v}")

    summary_lines += [
        "",
        "AWS RESOURCES THAT WILL BE CREATED",
        "  VPC (192.168.0.0/16) — public/private/Fargate subnets across 2 AZs",
        "  2× NAT Gateway + Elastic IP",
        "  EKS cluster (Auto Mode) with TWO workspace compute lanes:",
        "    • Fargate profile 'coder-workspaces'  (compute=fargate pods)",
        "    • EC2 Spot NodePool 'coder-ws-spot'   (compute=spot pods, auto-scaled)",
        "  Aurora PostgreSQL Serverless v2 cluster",
        "  EFS file system (encrypted) — persistent /home/coder for BOTH lanes",
        "  aws-ebs-csi-driver + aws-efs-csi-driver addons",
        "  CloudFront distribution + NLB",
        "  3× ECR repositories (claude-code, kiro-cli, challenge)",
        "  CodeBuild project (image build) + Lambda trigger",
        "  Secrets Manager secrets (admin password, session token, Bedrock key)",
        f"  IAM roles: FargatePodExecutionRole ({cluster}-fargate-pod-execution), {cluster}-workshop-user",
        "  KMS key for EKS secrets encryption",
        "  Coder Premium license applied (if CoderLicenseKey provided)",
        "",
        "TO DEPLOY",
        f"  bash {deploy_script_path.resolve()}",
        "",
        "  Or step-by-step:",
        f"  bash {deploy_script_path.resolve()} step1",
        f"  bash {deploy_script_path.resolve()} step2",
        "",
        "NOTE: CoderAdminPassword and CoderLicenseKey are REDACTED in core-parameters.json.",
        "      The wizard stores an auto-generated admin password in Secrets Manager.",
        "      If running deploy.sh manually, replace the REDACTED values first.",
    ]

    summary_path = out / "dry-run-summary.txt"
    summary_path.write_text("\n".join(summary_lines) + "\n")

    return DryRunOutput(
        output_dir=out,
        pipeline_params_path=pipeline_params_path,
        core_params_path=core_params_path,
        deploy_script_path=deploy_script_path,
        summary_path=summary_path,
    )
